Repository vercel/next-forge, pull requests merged in 2024-12, with the labels that each got.

#312 [Docs] Supabase database
  docs/database/overview.mdx
  docs/database/supabase.mdx
  docs/mint.json
  packages/database/index.ts
Labels: documentation

#325 New CMS package
  .github/workflows/build.yml
  .gitignore
  apps/api/.env.example
  apps/app/.env.example
  apps/web/.env.example
  apps/web/.gitignore
  apps/web/app/(home)/components/hero.tsx
  apps/web/app/blog/[slug]/page.tsx
  apps/web/app/blog/layout.tsx
  apps/web/app/blog/page.tsx
  apps/web/app/layout.tsx
  apps/web/app/legal/[slug]/page.tsx
  apps/web/app/legal/layout.tsx
  apps/web/app/sitemap.ts
  apps/web/components/mdx.tsx
  apps/web/components/sidebar.tsx
  apps/web/content-collections.ts
  apps/web/content/blog/gdpr.mdx
  apps/web/content/blog/radiant-ai.mdx
  apps/web/content/blog/series-a.mdx
  apps/web/content/legal/acceptable-use.mdx
  apps/web/content/legal/privacy.mdx
  apps/web/content/legal/terms.mdx
  apps/web/next.config.ts
  apps/web/package.json
  apps/web/tsconfig.json
  docs/cms/basehub.mdx
  docs/cms/content-collections.mdx
  docs/cms/overview.mdx
  docs/deployment/vercel.mdx
  docs/faq.mdx
  docs/mint.json
  docs/snippets/vercel.mdx
  packages/cms/.env.example
  packages/cms/components/body.tsx
  packages/cms/components/feed.tsx
  packages/cms/components/image.tsx
  packages/cms/components/toc.tsx
  packages/cms/components/toolbar.tsx
  packages/cms/index.ts
  packages/cms/next-config.ts
  packages/cms/package.json
  packages/cms/tsconfig.json
  packages/cms/typescript-config.json
  packages/env/index.ts
  pnpm-lock.yaml
  splash/.gitignore
  splash/app/components/features/basehub.svg
  splash/app/components/features/content-collections.png
  splash/app/components/features/index.tsx
  turbo.json
Labels: enhancement, minor

#320 New update command
  apps/web/public/blog/gdpr.png
  apps/web/public/blog/radiant-ai.png
  apps/web/public/blog/series-a.png
  docs/updates.mdx
  package.json
  pnpm-lock.yaml
  scripts/init.js
  scripts/init.mjs
Labels: minor

#329 Recipes
  apps/app/app/(authenticated)/components/header.tsx
  apps/app/app/(authenticated)/page.tsx
  docs/images/ai-chatbot.png
  docs/mint.json
  docs/recipes/ai-chatbot.mdx
  docs/recipes/analytics-app.mdx
  docs/recipes/chat-app.mdx
  docs/recipes/subscription-saas.mdx
  packages/ai/react.ts
Labels: documentation

#330 Tabs
  docs/features/ai.mdx
  docs/features/analytics/product.mdx
  docs/features/analytics/web.mdx
  docs/features/authentication.mdx
  docs/features/bi/metabase.mdx
  docs/features/bundle-analysis.mdx
  docs/features/cms.mdx
  docs/features/collaboration.mdx
  docs/features/cron.mdx
  docs/features/database.mdx
  docs/features/design-system/colors.mdx
  docs/features/design-system/components.mdx
  docs/features/design-system/dark-mode.mdx
  docs/features/design-system/provider.mdx
  docs/features/design-system/typography.mdx
  docs/features/documentation.mdx
  docs/features/email/clerk.mdx
  docs/features/email/resend.mdx
  docs/features/env.mdx
  docs/features/flags.mdx
  docs/features/formatting.mdx
  docs/features/observability/debugging.mdx
  docs/features/observability/error-capture.mdx
  docs/features/observability/logging.mdx
  docs/features/observability/uptime.mdx
  docs/features/payments.mdx
  docs/features/security/application.mdx
  docs/features/security/dependencies.mdx
  docs/features/security/headers.mdx
  docs/features/security/ip-geolocation.mdx
  docs/features/seo/json-ld.mdx
  docs/features/seo/metadata.mdx
  docs/features/seo/sitemap.mdx
  docs/features/storage.mdx
  docs/features/storybook.mdx
  docs/features/testing.mdx
  docs/features/webhooks.mdx
  docs/migrations/authentication/authjs.mdx
  docs/migrations/authentication/better-auth.mdx
  docs/migrations/cms/content-collections.mdx
  docs/migrations/database/drizzle.mdx
  docs/migrations/database/planetscale.mdx
  docs/migrations/database/prisma-postgres.mdx
  docs/migrations/database/supabase.mdx
  docs/migrations/database/turso.mdx
  docs/migrations/documentation/fumadocs.mdx
  docs/migrations/formatting/eslint.mdx
  docs/mint.json
  docs/setup/installation.mdx
  docs/setup/prerequisites.mdx
Labels: documentation

#331 Add Lemon Squeezy guide
  docs/migrations/payments/lemon-squeezy.mdx
  docs/mint.json
Labels: documentation

#343 Replace next-secure-headers with Nosecone for security headers
  apps/app/middleware.ts
  apps/app/package.json
  apps/web/middleware.ts
  docs/features/security/headers.mdx
  packages/next-config/index.ts
  packages/next-config/package.json
  packages/security/middleware.ts
  packages/security/package.json
  pnpm-lock.yaml
Labels: documentation

#349 Release 2.21 w/ Rate Limiting package
  docs/features/security/rate-limiting.mdx
  docs/images/rate-limit.png
Labels: minor

#353 Add uploadthing migration guide
  docs/features/storage.mdx
  docs/migrations/storage/upload-thing.mdx
  docs/mint.json
Labels: documentation
