Repository vercel/next-forge, pull requests merged in 2024-11, with the labels that each got.

#164 Debugging
  .github/workflows/build.yml
  .vscode/launch.json
  apps/_docs/content/docs/debugging.mdx
  apps/api/.env.example
  apps/app/.env.example
  apps/app/app/(unauthenticated)/layout.tsx
  apps/app/app/(unauthenticated)/sign-in/[[...sign-in]]/page.tsx
  apps/app/app/(unauthenticated)/sign-up/[[...sign-up]]/page.tsx
  apps/web/.env.example
  packages/design-system/lib/consts.ts
Labels: minor

#165 Add Unit Tests
  apps/_docs/content/docs/meta.json
  apps/_docs/content/docs/testing.mdx
  apps/app/__tests__/sign-in.test.tsx
  apps/app/__tests__/sign-up.test.tsx
  apps/app/app/(unauthenticated)/sign-in/[[...sign-in]]/page.tsx
  apps/app/app/(unauthenticated)/sign-up/[[...sign-up]]/page.tsx
  apps/app/package.json
  apps/app/vitest.config.ts
  package.json
  packages/design-system/lib/stripe.ts
  pnpm-lock.yaml
  turbo.json
Labels: minor

#166 Create CLI
  .autorc
  apps/_docs/app/(home)/components/installer.tsx
  apps/_docs/app/(home)/components/installer/bun.svg
  apps/_docs/app/(home)/components/installer/index.tsx
  apps/_docs/app/(home)/components/installer/npm.svg
  apps/_docs/app/(home)/components/installer/pnpm.svg
  apps/_docs/app/(home)/components/installer/yarn.svg
  apps/_docs/content/docs/setup.mdx
  index.js
  package.json
  pnpm-lock.yaml
Labels: minor

#181 Misc enhancements
  apps/_docs/content/docs/cron.mdx
  apps/_docs/content/docs/dark-mode.mdx
  apps/_docs/content/docs/database.mdx
  apps/_docs/content/docs/meta.json
  apps/_docs/content/docs/monitoring.mdx
  apps/_docs/content/docs/setup.mdx
  apps/api/app/cron/keep-alive/route.ts
  apps/api/app/global-error.tsx
  apps/api/app/webhooks/clerk/route.ts
  apps/app/app/global-error.tsx
  apps/app/app/layout.tsx
  apps/app/package.json
  apps/app/sentry.client.config.ts
  apps/web/app/contact/actions/contact.tsx
  apps/web/app/global-error.tsx
  apps/web/app/layout.tsx
  apps/web/components/mdx.tsx
  apps/web/components/sidebar.tsx
  apps/web/package.json
  packages/database/index.ts
  packages/design-system/components/mode-toggle.tsx
  packages/design-system/hooks/use-copy-to-clipboard.ts
  packages/design-system/hooks/use-enter-submit.ts
  packages/design-system/lib/email.ts
  packages/design-system/lib/error.ts
  packages/design-system/lib/fonts.ts
  packages/design-system/lib/format.ts
  packages/design-system/lib/resend.ts
  packages/design-system/lib/utils.ts
  packages/design-system/package.json
  packages/design-system/providers/index.tsx
  packages/design-system/typography.config.ts
  packages/email-templates/src/contact.tsx
  pnpm-lock.yaml
Labels: enhancement, patch

#187 feat: Add Arcjet security
  .github/workflows/build.yml
  apps/_docs/app/(home)/components/features/arcjet.svg
  apps/_docs/app/(home)/components/features/date-fns.svg
  apps/_docs/app/(home)/components/features/index.tsx
  apps/_docs/content/docs/meta.json
  apps/_docs/content/docs/security.mdx
  apps/api/.env.example
  apps/app/.env.example
  apps/app/app/(authenticated)/layout.tsx
  apps/app/lib/arcjet.ts
  apps/app/package.json
  apps/web/.env.example
  apps/web/middleware.ts
  apps/web/package.json
  packages/env/index.ts
  pnpm-lock.yaml
  turbo.json
Labels: minor

#196 chore(windows_setup): add windows setup script
  setup.bat
Labels: enhancement

#168 Co-author: Drizzle
  apps/_docs/app/docs/[[...slug]]/page.tsx
  apps/_docs/app/docs/components/coauthors.tsx
  apps/_docs/content/docs/drizzle.mdx
  apps/_docs/content/docs/meta.json
  apps/_docs/content/docs/planetscale.mdx
  apps/_docs/next.config.mjs
Labels: documentation

#212 Add Svix Webhooks
  .github/workflows/build.yml
  apps/api/.env.example
  apps/app/.env.example
  apps/app/app/(authenticated)/components/sidebar.tsx
  apps/app/app/(authenticated)/webhooks/page.tsx
  docs/mint.json
  docs/webhooks.mdx
  packages/env/index.ts
  packages/webhooks/index.ts
  packages/webhooks/lib/svix.ts
  packages/webhooks/package.json
  pnpm-lock.yaml
Labels: minor

#236 Remove root tsconfig.json
  tsconfig.json
Labels: patch

#235 Update `turbo.json` to improve cache hit ratios
  apps/api/package.json
  apps/app/package.json
  apps/web/package.json
  package.json
  turbo.json
Labels: patch

#237 Added anti-fraud advice
  docs/payments.mdx
Labels: documentation

#170 Turbo
  apps/api/app/layout.tsx
  apps/api/package.json
  apps/app/package.json
  apps/web/package.json
  apps/web/tsconfig.json
  docs/faq.mdx
  packages/typescript-config/nextjs.json
  pnpm-lock.yaml
  splash/package.json
Labels: minor

#249 Collaboration
  .coderabbit.yaml
  .github/workflows/build.yml
  apps/api/.env.example
  apps/app/.env.example
  apps/app/app/(authenticated)/components/avatar-stack.tsx
  apps/app/app/(authenticated)/components/collaboration-provider.tsx
  apps/app/app/(authenticated)/components/cursors.tsx
  apps/app/app/(authenticated)/components/sidebar.tsx
  apps/app/app/(authenticated)/page.tsx
  apps/app/app/actions/users/get.ts
  apps/app/app/actions/users/search.ts
  apps/app/app/api/collaboration/auth/route.ts
  apps/app/liveblocks.config.ts
  apps/app/package.json
  apps/web/.env.example
  docs/collaboration.mdx
  docs/images/authors/liveblocks/ctnicholas.jpg
  docs/images/authors/liveblocks/logo.jpg
  docs/images/collaboration.png
  docs/mint.json
  packages/collaboration/auth.ts
  packages/collaboration/config.ts
  packages/collaboration/hooks.ts
  packages/collaboration/package.json
  packages/collaboration/room.tsx
  packages/collaboration/tsconfig.json
  packages/design-system/tsconfig.json
  packages/env/index.ts
  pnpm-lock.yaml
  scripts/init.js
  splash/app/components/features/fumadocs.svg
  splash/app/components/features/index.tsx
  splash/app/components/features/liveblocks.svg
Labels: enhancement, minor

#182 Extract testing configuration into repo/testing package
  apps/app/package.json
  apps/app/vitest.config.ts
  docs/testing.mdx
  packages/testing/index.js
  packages/testing/package.json
  packages/testing/tsconfig.json
  pnpm-lock.yaml
  splash/app/components/apps/index.tsx
Labels: enhancement, help wanted

#268 Create Auth.js migration guide
  apps/api/app/webhooks/clerk/route.ts
  apps/api/app/webhooks/stripe/route.ts
  apps/api/package.json
  apps/app/app/(authenticated)/components/posthog-identifier.tsx
  apps/app/app/(authenticated)/components/sidebar.tsx
  apps/app/app/(authenticated)/layout.tsx
  apps/app/app/(authenticated)/page.tsx
  apps/app/app/actions/users/get.ts
  apps/app/app/actions/users/search.ts
  apps/app/app/api/collaboration/auth/route.ts
  apps/app/middleware.ts
  apps/app/package.json
  apps/web/middleware.ts
  apps/web/package.json
  docs/authentication/authjs.mdx
  docs/authentication/overview.mdx
  docs/mint.json
  packages/auth/client.ts
  packages/auth/middleware.ts
  packages/auth/package.json
  packages/auth/server.ts
  packages/feature-flags/lib/create-flag.ts
  packages/feature-flags/package.json
  packages/webhooks/lib/svix.ts
  packages/webhooks/package.json
  pnpm-lock.yaml
Labels: documentation

#285 Symlink environment variables
  .env.example
  .github/workflows/build.yml
  apps/api/.env.example
  apps/api/.env.local
  apps/api/.gitignore
  apps/app/.env.example
  apps/app/.env.local
  apps/app/.gitignore
  apps/web/.env.local
  apps/web/.gitignore
  docs/authentication/authjs.mdx
  docs/database/planetscale.mdx
  docs/database/turso.mdx
  docs/env.mdx
  docs/setup.mdx
  packages/database/.env
  packages/database/.env.example
  scripts/init.js
Labels: minor
